### ISSUE TITLE
LCN fields not populating

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-leadpoint#13]
A couple of POSTs into the LeadPoint integration have given me strange results:

{
outcome: "failure"
reason: "Failed rules due to first name matching last name"
lead: {
id: "555b51e78bacb6a223b29696"
}-
}

When the POST data does not reflect anything relevant to that. Generally I test with just a few variables, so this is why there's such a small amount of data in the POST

POST /flows/53c997339d29c9787d00006b/sources/53d7ba989869170001000002/submit HTTP/1.0
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
Connection: close
Content-Length: 92
Content-Type: application/x-www-form-urlencoded

 first_name=Chester&last_name=Tester&phone_1=(773)+288-2161&email=chestertester_951@aol.com

### Can anyone tell me why this is happening?

https://next.leadconduit.com/events/555b51e78bacb6a223b29696

**Comment by zalary** [comment]
This integration is expecting fname and lname on the inbound, which the integration then assigns to  first_name and last_name.  Since these aren't being populated, when it gets to the filter it triggers that failure because they technically ARE they same (i.e. both blank)

So try passing fname and lname and see if that helps

**Comment by zalary** [comment]
You can find the fields the integration expects at/around:

https://github.com/activeprospect/leadconduit-integration-leadpoint/blob/master/src/inbound.coffee#L46

That part of the code should be fairly straightforward as to what maps to what

**Comment by kcaponeAP** [comment]
i clearly missed the coffee boat this morning tyvm.
