### ISSUE TITLE
Please add ADD_CASH to LeadPoint integration

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-leadpoint#15]
LeadPoint has informed us that the field ADD_CASH is for "How much additional cash do you wish to borrow?" 

Values: number

Example: 
ADD_CASH=20000

Needed for current customer

**Comment by ros3bud** [comment]
@kcaponeAP - which internal field should this map to? Or is a new one needed?

**Comment by kcaponeAP** [comment]
mortgage.loan.cash_out

**Comment by ros3bud** [comment]
updated in PR #27
