### ISSUE TITLE
Please add OCC_STAT to the LeadPoint integration

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-leadpoint#19]
LeadPoint has informed us that OCC_STAT is the employment/occupational status for a lead. Please use this for 'employment_status'

Allowable values are: "employed", "self_emp", "retired", "unemployed"

Example: OCC_STAT=employed

**Comment by ros3bud** [comment]
@kcaponeAP - are the allowable values what LeadPoint accepts? If that is the case, is it possible that we may see self_employed or a similar variation passed in?

**Comment by kcaponeAP** [comment]
the allowable values are the only values that leadpoint will be sending for OCC_STAT per their documentation
