### ISSUE TITLE
Please add PREF_CALLTIME to LeadConduit Integration

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-leadpoint#23]
We have been informed by LeadPoint that PREF_CALLTIME time is the Preferred time to call. Please route this as follows to LCN field  'time_to_contact'

Desc: Preferred time to call	
field: PREF_CALLTIME	
type: string	

Allowed Values Only:

morning_primary
afternoon_primary
evening_primary
morning_secondary
afternoon_secondary
evening_secondary

**Comment by ros3bud** [comment]
@kcaponeAP - can you please confirm whether they will be passing PREF_CALL or PREF_CALLTIME?

**Comment by kcaponeAP** [comment]
Sure thing! It is indeed PREF_CALLTIME. Updated in the description also.

**Comment by ros3bud** [comment]
Thanks!

**Comment by ros3bud** [comment]
We need more information about primary and secondary phone numbers.

**Comment by kcaponeAP** [comment]
Here are the definitions for phone numbers we are currently using in LCN:

PRI_PHONE_10 = 	Primary Phone first 10 digits
SEC_PHONE_10 = Secondary Phone first 10 digits

& an example of a lead: 
https://next.leadconduit.com/events/5570a90204451f73651e23f5?source_id=53d7ba989869170001000002&type=source&start=2015-06-01&end=2015-06-09

Does this help at all? I can dig up more info if needed :)

**Comment by ros3bud** [comment]
Upon further research, it is ok to parse morning, afternoon and evening from pref_calltime and to leave phone_1 and phone_2 as they are.

**Comment by alexkwolfe** [comment]
What if `PREF_CALLTIME=morning_secondary`? Don't we want `phone_1` to contain the `SEC_PHONE_10` value in that case?

**Comment by ros3bud** [comment]
Yes. However since they are already passing primary and secondary phone numbers, this should not happen. Key word being "should" - so ok, I can account for the possibility in the integration.

**Comment by alexkwolfe** [comment]
I don't understand why this should not happen. I would think that if `PREF_CALLTIME=morning_secondary` that the preferred contact number is `SEC_PHONE_10`. If that's the case, then I feel like it should go in our `phone_1` field.

**Comment by kcaponeAP** [comment]
I asked LeadPoint directly, how often are people passing morning_secondary, afternoon_secondary and evening_secondary and what is the expected behaviour. Their response was:

"Since the first option is at "morning_primary", most people probably leave it as is."
