### ISSUE TITLE
Please add MIN_PAY to LeadPoint integration

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-leadpoint#24]
We have recently been informed that MIN_PAY is described as Minimum Monthly Debt Pmt. Please route this to the internal LCN field mortgage.application.monthly_debt_payment

Example: 
MIN_PAY= 1200
integer or range

**Comment by ros3bud** [comment]
@kcaponeAP - we'll need to know whether this is expected to be an integer or a range.

**Comment by ros3bud** [comment]
Ok, because the customer will literally pass either an integer or a range, I need to do a bit more research about how to handle the incoming values for this one.

**Comment by alexkwolfe** [comment]
You can safely use a range type.
