### ISSUE TITLE
PHON versus PHONE 

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-leadpoint#32]
The LeadPoint integration was built to accept PRI_PHONE for phone_1 and SEC_PHONE for phone_2. LeadPoint actually sends (respectively) PRI_PHON & SEC_PHONE.

Can we have this updated in the integration?

Integration worksheet: https://docs.google.com/spreadsheets/d/1ODNubhI1C2M4i0YtDRAP0e-1z_Swo6iZwBDxYgRDlC0/edit#gid=2053149198

We have a customer ready to go live and they are waiting on this fix.

**Comment by alexj** [comment]
@ros3bud can you knock this out? This seems like it will be a quick bit of work and will let the customer roll forward.

**Comment by ros3bud** [comment]
Yes, will do.

**Comment by ros3bud** [comment]
@kcaponeAP, can you please give me an example of a lead where this was broken?

**Comment by ros3bud** [comment]
@kcaponeAP, can you please give me an example of a lead where this was broken?

**Comment by kcaponeAP** [comment]
Example: 

https://next.leadconduit.com/events/55b16ebf35e1f84b61a458bc

**Comment by kcaponeAP** [comment]
In the example above...the phone numbers are not parsed correctly by LCN because they are specified as PRI_PHONE/SEC_PHONE in the way the integration is built, when the actual specs from LeadPoint are PRI_PHON/SEC_PHON.

**Comment by zalary** [comment]
isn't LeadPoint successfully delivering leads to another flow?

**Comment by kcaponeAP** [comment]
No that never got off the ground with the other client.

**Comment by ros3bud** [comment]
I see that SEC_PHONE also needs to be updated.
