### ISSUE TITLE
Cannot view technical details in LeadPoint postback

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-leadpoint#34]
In my recent test, I was not able to view the technical details in the LeadPoint postback integration.

https://next.leadconduit.com/events/55b92948dc149495026676bb?event_id=55b92948dc149495026676bc

is this a bug?

**Comment by alexkwolfe** [comment]
Sort of. When you sent that lead you had the "LeadPoint Feedback" variable mapped to `DISCONNECTED_PHONE`. The integration didn't know how to convert that value to the right feedback code for LeadPoint. 

I see that the mapping has now been changed to `Disconnected Phone`. This should work the way you expect. If something is still not working, please reopen this issue.
