### ISSUE TITLE
Question on what is required in the leadpoint postback mappings

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-leadpoint#36]
The mappings state that there are 4 required fields for leadpoint:

![screen shot 2015-07-29 at 2 38 54 pm](https://cloud.githubusercontent.com/assets/8238417/8967889/9c4f2410-35ff-11e5-926d-43003f9516d6.png)

However, their documentation states:

Each HTTP post submission needs to contain the following 3 parameters:

1. Your Account ID (AID=974).  Your account ID can be found at the top right corner of any page within your LeadPoint account.

2. LeadPoint Lead ID (Lead_ID=1234).  This is the LeadPoint ID number for the lead that's being reported on. 

3. Feedback Reason Code (Feedback=107).  Please refer to the list of feedback reasons below for all applicable codes.  LeadPoint's system will accept either the "Feedback Code" or the "Feedback String" noted below.*

New document here on postback returns:

https://docs.google.com/document/d/1YLckFSZD6vIw5JvsmeJc2dCL3d_aleWoz2srQMGS8Kw/edit#

**Comment by kcaponeAP** [comment]
This is super misleading documentation because in their example, there is another ID, which is listed as 151 ... 151 must be the member ID? There must be member ID and account ID. 

https://member.leadpoint.com/151/feedback/import.dt?AID=974&LEAD_ID=300426&FEEDBACK=108

Thoughts?

**Comment by zalary** [comment]
151 is the member id and 974 is the Aid. So try using those 2 numbers?

**Comment by kcaponeAP** [comment]
Okay, I've managed to get this to work with the help of their QA department. Closing this issue :)
