### ISSUE TITLE
Four new fields needed in the integration

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-integration-leadpoint#40]
Please add these fields to the LeadPoint integration:
* PROP_SQFT
* PROP_BEDS
* PROP_BATHS
* PROP_URL

Field Name|Description|Req'd|Type|Example
---------------|----------------|-------|-------|-----------
PROP_SQFT|Square Footage|No|numeric|3000
PROP_BEDS|Number of Beds|No|integer|3
PROP_BATHS|Number of Baths|No|numeric|3.5
PROP_URL|Property Link|No|string

**Comment by ros3bud** [comment]
Looks like we're going to need to add new standard fields before adding these fields to the integration.

**Comment by ros3bud** [comment]
To get the ball rolling here, I propose the following new Mortgage fields - feel free to chime in @alexj: 

Name / Data Type / Description
Property Square Footage / string / Property square footage
Property Bedrooms / integer / Property number of bedrooms
Property Bathrooms / integrer / Property number of bathrooms
Property Url / string / Property listing url

@alexkwolfe - do I have your approval to add these to the standard fields library?

**Comment by alexkwolfe** [comment]
Yes.

**Comment by alexkwolfe** [comment]
@alexj, do you have an opinion on whether we should have "square footage" or "square feet" as the field name?  I'd think people would be more familiar with the latter term and when searching would most likely expect that variation. Thoughts?

**Comment by Nicolemt** [comment]
My vote is for square feet. Could they find it under either search term though?

**Comment by alexj** [comment]
Square feet makes the most sense to me. To Nicole's point, it would be good to include the phrase "square footage" in the description, in the hopes that it is indexed by the search functionality (is it?).

**Comment by alexkwolfe** [comment]
At docs.leadconduit.com, the field search does consider the description.

**Comment by ros3bud** [comment]
Solved in version 1.7.0
