### ISSUE TITLE
Please add MTG_TWO_INT 

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-leadpoint#51]
LeadPoint has begun to send MTG_TWO_INT in their leads. 

https://next.leadconduit.com/events/5616a51d925306170a6ab7a8?source_id=53d7ba989869170001000002&type=source

Example: MTG_TWO_INT=3.5

Please add this to the internal LCN field, as per https://github.com/activeprospect/leadconduit-fields/issues/64

**Comment by ros3bud** [comment]
Thanks for pointing out that the internal field needed to be added @kcaponeAP!

**Comment by ros3bud** [comment]
Solved in 1.8.0
